service: alexa-cycling-clothier

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'us-west-2'}

functions:
  cycling_clothier:
    handler: handler.lambda_handler
    events:
      - alexaSkill: amzn1.ask.skill.64521cab-ca3c-4bb6-97ab-e1b7031a2146

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
